# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gamifiedcourse_management", "0004_remove_gamifiedcourse_sections_and_more"),
        ("accounts", "0003_delete_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenge_management", "0002_challenge_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankofchallenges",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="bankofchallenges",
            name="tools",
        ),
        migrations.AddField(
            model_name="challenge",
            name="BankOfChallenges",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="challenge_management.bankofchallenges",
            ),
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="admin",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="evaluated_by",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evaluated_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Evaluation",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.AddField(
            model_name="challenge",
            name="admin",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.admin",
            ),
        ),
    ]
