# Generated by Django 4.1.7 on 2023-04-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_badge"),
        ("challenge_management", "0003_remove_bankofchallenges_challenge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankOfQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "instructor",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.instructor",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="BankOfChallenges",
        ),
        migrations.DeleteModel(
            name="BankOfChallenges",
        ),
        migrations.AddField(
            model_name="challenge",
            name="BankOfQuestions",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="challenge_management.bankofquestions",
            ),
        ),
    ]
