# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_developer_badges"),
        ("learningpath_management", "0002_learningpath_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="learningpath",
            name="admin",
        ),
        migrations.AddField(
            model_name="learningpath",
            name="admin",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.admin",
            ),
            preserve_default=False,
        ),
    ]
