# Generated by Django 4.1.7 on 2023-04-01 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="reward_points",
        ),
        migrations.AddField(
            model_name="challenge",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("1 star", "Level 1"),
                    ("2 star", "Level 2"),
                    ("3 star", "Level 3"),
                    ("4 star", "Level 4"),
                    ("5 star", "Level 5"),
                ],
                default="1 star",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="haveGrader",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenge",
            name="isPlanned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenge",
            name="solution",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="challenge",
            name="topic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="challenge",
            name="type",
            field=models.CharField(
                choices=[("Normal challenge", "Type 1"), ("Job challenge", "Type 2")],
                default="Normal challenge",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_challenges", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
