# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="badges",
        ),
    ]
