# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_developer_badges"),
        ("gamification_management", "0003_remove_gamification_badges_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Badge",
        ),
    ]
