# Generated by Django 4.1.7 on 2023-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("gamifiedcourse_management", "0002_gamifiedcoursecontent_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamifiedcoursecontent",
            name="admin",
        ),
        migrations.AddField(
            model_name="gamifiedcourse",
            name="admin",
            field=models.ManyToManyField(to="accounts.admin"),
        ),
    ]
