# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_badge"),
        (
            "learningpath_management",
            "0003_remove_learningpath_admin_learningpath_admin",
        ),
        (
            "gamifiedcourse_management",
            "0003_remove_gamifiedcoursecontent_admin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamifiedcourse",
            name="sections",
        ),
        migrations.AddField(
            model_name="gamifiedcourse",
            name="Instructor",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gamified_courses",
                to="accounts.instructor",
            ),
        ),
        migrations.RemoveField(
            model_name="gamifiedcourse",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="gamifiedcourse",
            name="learningpath",
        ),
        migrations.DeleteModel(
            name="GamifiedCourseContent",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.AddField(
            model_name="gamifiedcourse",
            name="admin",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.admin",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamifiedcourse",
            name="learningpath",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamified_courses",
                to="learningpath_management.learningpath",
            ),
            preserve_default=False,
        ),
    ]
