# Generated by Django 4.1.7 on 2023-04-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge_management", "0003_remove_bankofchallenges_challenge_and_more"),
        ("gamifiedcourse_management", "0004_remove_gamifiedcourse_sections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamifiedcourse",
            name="challenges",
            field=models.ManyToManyField(to="challenge_management.challenge"),
        ),
    ]
