# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification_management", "0002_notification_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="admin",
        ),
    ]
