# Generated by Django 4.1.7 on 2023-04-03 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("offer_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Gamification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("badge_eggs", models.JSONField(default=list)),
                ("max_eggs_per_challenge", models.IntegerField(default=0)),
                ("min_eggs_per_challenge", models.IntegerField(default=0)),
                ("max_eggs_per_learningpath", models.IntegerField(default=0)),
                ("min_eggs_per_learningpath", models.IntegerField(default=0)),
                (
                    "time_to_restore_life_system",
                    models.DurationField(default=datetime.timedelta(days=2)),
                ),
                ("badges", models.ManyToManyField(to="accounts.badge")),
                (
                    "pycoins",
                    models.ManyToManyField(to="gamification_management.pricing"),
                ),
            ],
        ),
    ]
