# Generated by Django 4.1.7 on 2023-05-16 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gamification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("badge_eggs", models.JSONField(default=list)),
                ("max_eggs_per_challenge", models.IntegerField(default=0)),
                ("min_eggs_per_challenge", models.IntegerField(default=0)),
                ("max_eggs_per_learningpath", models.IntegerField(default=0)),
                ("min_eggs_per_learningpath", models.IntegerField(default=0)),
                (
                    "time_to_restore_life_system",
                    models.DurationField(default=datetime.timedelta(days=2)),
                ),
            ],
        ),
    ]
