# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_developer_badges"),
        ("gamification_management", "0002_gamification_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamification",
            name="badges",
        ),
        migrations.RemoveField(
            model_name="gamification",
            name="pycoins",
        ),
        migrations.RemoveField(
            model_name="gamification",
            name="admin",
        ),
        migrations.DeleteModel(
            name="Pricing",
        ),
        migrations.AddField(
            model_name="gamification",
            name="admin",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.admin",
            ),
        ),
    ]
