# Generated by Django 4.1.7 on 2023-04-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_badge"),
        ("challenge_management", "0003_remove_bankofchallenges_challenge_and_more"),
        ("job_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="challenge",
        ),
        migrations.AddField(
            model_name="joboffer",
            name="participants",
            field=models.ManyToManyField(to="accounts.developer"),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="job_challenge",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_offers",
                to="challenge_management.challenge",
            ),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="recruiter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruiter",
                to="accounts.recruiter",
            ),
        ),
    ]
